<?php
/**
 * MyBB 1.8.x Official Czech Language Pack
 * Copyright © 2014-2018 MyBB Group 
 * All Rights Reserved 
 *
 * Issues and pull request belongs to the https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/
 */

$l['nav_online'] = "Kdo je přítomný";
$l['nav_onlinetoday'] = "Kdo byl dnes přihlášen";

$l['viewing_announcements'] = "Zobrazuje oznámení <a href=\"{1}\">{2}</a>";
$l['viewing_announcements2'] = "Zobrazuje oznámení fóra";
$l['viewing_attachment'] = "Zobrazuje přílohy";
$l['viewing_attachment2'] = "Zobrazuje <a href=\"attachment.php?aid={1}\" target=\"_blank\">přílohy</a> v tématu <a href=\"{3}\">{2}</a>";
$l['viewing_calendar'] = "Zobrazuje <a href=\"calendar.php\">kalendář</a>";
$l['viewing_event'] = "Zobrazuje události";
$l['viewing_event2'] = "Zobrazuje události <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">Přidává události</a>";
$l['editing_event'] = "Upravuje události";
$l['viewing_contact_us'] = "Zobrazuje <a href=\"contact.php\">kontakty</a>";
$l['editing_post'] = "Upravuje příspěvky";
$l['viewing_forum'] = "Zobrazuje fóra";
$l['viewing_forum2'] = "Zobrazuje fóra <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "Přesměrování na <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "Prohlíží hlavní stránku <a href=\"index.php\">{1}</a>";
$l['activating_account'] = "Aktivuje účet";
$l['viewing_profile'] = "Zobrazuje profil";
$l['viewing_profile2'] = "Zobrazuje profil uživatele <a href=\"{1}\">{2}</a>";
$l['registering'] = "<a href=\"member.php?action=register\">Registruje se</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">Přihlašuje se</a>";
$l['logging_in_plain'] = "Přihlašuje se";
$l['logging_out'] = "Odhlašuje se";
$l['emailing_user'] = "Posílá e-mail uživateli";
$l['rating_user'] = "Hodnotí uživatele";
$l['viewing_memberlist'] = "Zobrazuje <a href=\"memberlist.php\">seznam uživatelů</a>";
$l['viewing_whoposted'] = "Zobrazuje kdo psal příspěvky";
$l['viewing_whoposted2'] = "Zobrazuje kdo přispěl do tématu <a href=\"{1}\">{2}</a>";
$l['marking_read'] = "<a href=\"misc.php?action=markread&amp;my_post_key={1}\">Označuje fóra jako přečtená</a>";
$l['viewing_helpdocs'] = "Zobrazuje <a href=\"misc.php?action=help\">Nápovědu</a>";
$l['viewing_buddylist'] = "Zobrazuje <a href=\"misc.php?action=buddypopup\">Seznam přátel</a>";
$l['viewing_smilies'] = "Zobrazuje <a href=\"misc.php?action=smilies\">smajlíky</a>";
$l['viewing_syndication'] = "Zobrazuje <a href=\"misc.php?action=syndication\">RSS odběry</a> Page";
$l['replying_thread'] = "Odpovídá na téma";
$l['replying_thread2'] = "Odpovídá na téma <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "Zakládá téma";
$l['posting_thread2'] = "Zakládá téma v <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "Zobrazuje <a href=\"online.php\">Kdo je přítomný</a>";
$l['viewing_woltoday'] = "Zobrazuje <a href=\"online.php?action=today\">Kdo byl dnes přihlášen</a>";
$l['creating_poll'] = "Vytváří novou anketu";
$l['editing_poll'] = "Upravuje anketu";
$l['viewing_pollresults'] = "Zobrazuje výsledky ankety";
$l['voting_poll'] = "Hlasuje v anketě";
$l['using_modtools'] = "Moderuje";
$l['sending_pm'] = "Odesílá soukromé zprávy";
$l['reading_pm'] = "Čte soukromé zprávy";
$l['editing_pmfolders'] = "Upravuje složky SZ";
$l['using_pmsystem'] = "Používá SZ";
$l['reporting_post'] = "Ohlašuje příspěvek";
$l['searching_forum'] = "<a href=\"search.php\">Hledá</a> ve fóru {1}";
$l['reading_thread'] = "Čte téma";
$l['reading_thread2'] = "Čte téma <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "Zobrazuje tým fóra";
$l['viewing_stats'] = "Zobrazuje statistiky fóra";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">Aktualizuje profil</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">Aktualizuje nastavení</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">Upravuje podpis</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">Mění avatar</a>";
$l['viewing_subscriptions'] = "Zobrazuje <a href=\"usercp.php?action=subscriptions\">odběry témat</a>";
$l['viewing_favorites'] = "Zobrazuje <a href=\"usercp.php?action=favorites\">oblíbená témata</a>";
$l['editing_pad'] = "Upravuje <a href=\"usercp.php?action=notepad\">osobní poznámky</a>";
$l['editing_password'] = "Upravuje <a href=\"usercp.php?action=password\">heslo</a>";
$l['user_cp'] = "Zobrazuje <a href=\"usercp.php\">Nastavení uživatele</a>";
$l['viewing_portal'] = "Zobrazuje <a href=\"portal.php\">Portál</a> Page";
$l['viewing_noperms'] = "Zobrazuje nepovolené stránky";
$l['unknown_location'] = "<a href=\"{1}\">Neznámá lokace</a>";
$l['giving_reputation'] = "Uděluje hodnocení <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report'] = "Zobrazuje <a href=\"{1}\">hodnocení uživatele {2}</a>";
$l['viewing_reputation_report2'] = "Zobrazuje hodnocení";
$l['member_resendactivation'] = "Odesílá aktivační e-mail";
$l['member_lostpw'] = "Obnovuje <a href=\"member.php?action=lostpw\">zapomenuté heslo</a>";
$l['sending_thread'] = "Odesílá téma příteli";
$l['page'] = "Stránka";
$l['users_online'] = "Kdo je přítomný";
$l['on_username'] = "Uživatelské jméno";
$l['time'] = "Čas";
$l['location'] = "Lokace";
$l['online_today'] = "Kdo byl dnes přihlášen";
$l['refresh_page'] = "Obnovit stránku";
$l['online_online_plural'] = "uživatelé(ů)";
$l['online_online_singular'] = "uživatel";
$l['online_member_plural'] = "uživatelé(ů)";
$l['online_member_singular'] = "uživatel";
$l['online_anon_plural'] = "jsou";
$l['online_anon_singular'] = "je";
$l['online_guest_plural'] = "hosté(ů)";
$l['online_guest_singular'] = "host";
$l['online_count'] = "Aktivních {1} {2} během uplynulých {3} minut (z toho {4} {5}, {6} neviditelných a {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Jméno hostitele:";
$l['if_resolvable'] = "(lze-li zjistit)";
$l['admin_options'] = "Nastavení administrace";
$l['search_regip_users'] = "Hledat uživatele, kteří se registrovali pod touto IP adresou";
$l['search_postip_users'] = "Hledat uživatele, kteří publikovali pod touto IP adresou";
$l['lookup'] = "[hledat]";
$l['member_online_today'] = "<strong>1</strong> uživatel byl dnes přihlášen";
$l['members_were_online_today'] = "<strong>{1}</strong> uživatelé(ů) byli(o) dnes přihlášeni(o)";
$l['member_online_hidden'] = " ({1} uživatel byl skrytý)";
$l['members_online_hidden'] = " ({1} uživatelé(ů) byli(o) skrytí(o)";
$l['rating_thread'] = "Hodnotí téma";
$l['viewing_imcenter'] = "Zobrazuje IM Center";
$l['managing_favorites'] = "Spravuje oblíbená témata";
$l['managing_subscriptions'] = "Spravuje odebíraná témata";
$l['managing_group'] = "Spravuje uživatelské skupiny";
$l['viewing_modcp'] = "Zobrazuje nastavení moderátora";
$l['viewing_modlogs'] = "Zobrazuje logy moderátora";
$l['managing_announcements'] = "Spravuje oznámení";
$l['search_for_user'] = "Hledá uživatele";
$l['managing_warninglogs'] = "Spravuje logy varování";
$l['searching_ips'] = "Hledá IP adresy";
$l['viewing_reports'] = "Zobrazuje oznámené příspěvky";
$l['adding_announcement'] = "Přidává oznámení";
$l['deleting_announcement'] = "Odstraňuje oznámení";
$l['editing_announcement'] = "Upravuje oznámení";
$l['managing_modqueue'] = "Spravuje frontu moderování";
$l['editing_user_profiles'] = "Upravuje uživatelské profily";
$l['managing_bans'] = "Spravuje bany";
$l['revoking_warning'] = "Ruší varování";
$l['warning_user'] = "Varuje uživatele";
$l['viewing_warning'] = "Zobrazuje varování";
$l['managing_warnings'] = "Spravuje varování";
$l['changing_dst'] = "Mění nastavení letního času";
$l['printing_thread'] = "Tiskne téma";
$l['printing_thread2'] = "Tiskne téma <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Spravuje seznamu (ne)přátel";