<?php
/**
 * Author: Dark Neo
 * Plugin: Thanks System
 * Version: 2.5.3
 * Plugin Language File: english
 */
$l['thx_title'] = "Thanks system";
$l['thx_desc'] = "Add a new button on forums where apply to thanks users";
$l['thx_config'] = "Configure Plugin";
$l['thx_config_alerts'] = "You have installed MyAlerts but you have to configure propertly to use with this plugin...";
$l['thx_config_alerts_thx'] = "Thank you mybb plugin enabled and already to use (MyAlerts was detected and is a version compatible with MyBB 1.8)";
$l['thx_config_alerts_thx_config'] = "Plugin activated but you must configure plugins options to make MyAlerts compatible.";
$l['thx_config_alerts_none'] = "Thank you mybb plugin it's already to be used, you can add <a href=\"{1}\"> ( MyAlerts 2.0 )</a> to add new functions on plugin";
$l['thx_config_alerts_missing'] = "You must integrate this plugin with MyAlerts to make it works propertly {1}";
$l['thx_config_alerts_force_all'] = "Force enable alerts for all users";
$l['thx_admin_thx_group'] = "Thank you system adjustments";
$l['thx_admin_thx_group_opt1'] = "Thanks ammount per day by usergroup:  ";
$l['thx_admin_thx_group_opt2'] = "Reputation points to give when use thanks button:  ";
$l['thx_admin_thx_group_opt3'] = "Newpoints earned when user thanks your posts:  ";
$l['thx_admin_thx_group_opt4'] = "Newpoints gived when user use thanks button:  ";
$l['thx_disabled'] = "Plugin Disabled";
$l['thx_opt_title'] = "[Plugin] Thanks system";
$l['thx_opt_desc'] = "Configuration options";
$l['thx_opt_enable'] = "Enable/Disable plugin";
$l['thx_opt_enable_desc'] = "Enable or disable plugin (do not delete thanks)";
$l['thx_count_title'] = "Show thanks count";
$l['thx_count_desc'] = "Shows thanks gived and received on your postbit";
$l['thx_counter_title'] = "Show thanks counter";
$l['thx_counter_desc'] = "Shows counter for thanks received on every post";
$l['thx_del_title'] = "Users can delete given thanks";
$l['thx_del_desc'] = "Users can delete every one message they give to another user";
$l['thx_date_title'] = "Show date on hover";
$l['thx_date_desc'] = "Show thanked date, on mouse over";
$l['thx_hide_title'] = "Enable [???] tag";
$l['thx_hide_desc'] = "Hide contents between <b>[???]</b> tag, until you thank post. <div style=\"float:right;\"><b>Use next option to set hide tag</b></div>";
$l['thx_hidetag_title'] = "Hide tag to use on your messages Ex: [???]";
$l['thx_hidetag_desc'] = "Set tag for hide contents on posts <b>[???]</b>, like (MyCode).<div style=\"float:right;\"><b>You have to enable previous option to use this.<br />Ex: hide, lock, guest, etc...</b></div>";
$l['thx_hidetag_value'] = "hide";
$l['thx_ebutton_title'] = "Editor Button";
$l['thx_ebutton_desc'] = "Show hide MyCode button (You have to enable hide tag.)";
$l['thx_fid_title'] = "Forums where apply this mod";
$l['thx_fid_desc'] = "Select forums where you want to use this system, separated by comma.";
$l['thx_gid_title'] = "Usergrous who can view hide tag contents [???]";
$l['thx_gid_desc'] = "Usergroups who can see without thanks contents inside hide tag.<div style=\"float:right;\"><b>Default: (Admins)</b></div>";
$l['thx_ngid_title'] = "Usergroups who can not see hide tag content and not use thanks system";
$l['thx_ngid_desc'] = "Usergroups who can not see any hide tag contents. Can not use thanks system and can not see thanks and thanked times <div style=\"float:right;\"><b>Def: (Guest, Acount whitout activation, Banned users)</b></div>";
$l['thx_rep_title'] = "Enable reputation integration?";
$l['thx_rep_desc'] = "Use reputation system on thanks, if you enable 2nd or 4th option you have to install MyAlerts plugin from Euantor";
$l['thx_rep_op1'] = "Disabled";
$l['thx_rep_op2'] = "Integration with MyAlerts";
$l['thx_rep_op3'] = "Integration with Reputation";
$l['thx_rep_op4'] = "Integration with Reputation + MyAlerts";
$l['thx_limit_title'] = "Limit thanks per day";
$l['thx_limit_desc'] = "Set the options on usergroups of max ammount by usergroup (if set to No its recomended to disable thanks per day task)";
$l['thx_recount'] = "Recount Thanks";
$l['thx_can_recount'] = "Enable Recount Thanks";
$l['thx_recount_do'] = "Thanks Recount";
$l['thx_upgrade_do'] = "Upgrade Thanks Count";
$l['thx_recount_task_title'] = "Task";
$l['thx_recount_task_desc'] = "Send/Cicle";
$l['thx_recount_update'] = "Recount Thanks";
$l['thx_recount_update_desc'] = "Upgrade thanks given by users on threads and posts";
$l['thx_recount_update_button'] = "Update";
$l['thx_counter_update'] = "Update Counters";
$l['thx_counter_update_desc'] = "Update count of thanked threads";
$l['thx_confirm_next'] = "<p>Click on CONTINUE to do thanks recount.</p><p>If you are on this page you have to recount more threads and/or posts</p><p>Click on Continue Buttoun until this proccess has finish.</p>";
$l['thx_confirm_button'] = "Continue";
$l['thx_confirm_page'] = "page #: ";
$l['thx_confirm_elements'] = "Elements to Proccess";
$l['thx_update_psuccess'] = "Thanks Reconstruction Succeed";
$l['thx_update_tsuccess'] = "Thanks Recount Proccess Succeed";
$l['thx_thankyou'] = "Thanks for this post";
$l['thx_alerts_title'] = "Add an alert when someone has thanked a post?";
$l['thx_alerts_title_desc'] = "If you enable this, everytime you have a new notificaction when someone has thanked your posts (Require Thanks System plugin)";
$l['thx_alerts_install_error'] = "You need to install MyAlerts to add an alert message, if you install MyAlerts, deactivate and activate this plugin again, this won't delete thanks given or received and give you a new option to use Thankyou System with MyAlerts";
$l['thx_antiflood_title'] = "Enable antiflood";
$l['thx_antiflood_desc'] = "Enables antiflood protection in seconds for every thank given, choose disabled to not use or time in seconds to be used";
$l['thx_antiflood_op1'] = "Disabled";
$l['thx_antiflood_op2'] = "15";
$l['thx_antiflood_op3'] = "30";
$l['thx_antiflood_op4'] = "45";
$l['thx_antiflood_op5'] = "60";